name: flutter_book
description: flutter_book

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^1.1.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  flutter_slidable: ^0.5.7
  intl: ^0.17.0
  image_picker: 0.6.3+1
  flutter_calendar_carousel: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


